## Copyright (c) 2015 SONATA-NFV, 2017 5GTANGO [, ANY ADDITIONAL AFFILIATION]
## ALL RIGHTS RESERVED.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Neither the name of the SONATA-NFV, 5GTANGO [, ANY ADDITIONAL AFFILIATION]
## nor the names of its contributors may be used to endorse or promote
## products derived from this software without specific prior written
## permission.
##
## This work has been performed in the framework of the SONATA project,
## funded by the European Commission under Grant number 671517 through
## the Horizon 2020 and 5G-PPP programmes. The authors would like to
## acknowledge the contributions of their colleagues of the SONATA
## partner consortium (www.sonata-nfv.eu).
##
## This work has been performed in the framework of the 5GTANGO project,
## funded by the European Commission under Grant number 761493 through
## the Horizon 2020 and 5G-PPP programmes. The authors would like to
## acknowledge the contributions of their colleagues of the 5GTANGO
## partner consortium (www.5gtango.eu).
# encoding: utf-8
base_path: /api/v3
paths:
  /: 
    site: http://localhost:5000 #son-gtkapi:5000
  /docs:
    site: http://son-gtkapi:5000/api/doc
  /admin/logs:
    site: http://son-gtkapi:5000/api/v2/admin/logs
  /admin/available-services:
    site: http://son-gtkapi:5000/api/v2/available-services
  /users/api/v1/userinfo:
    site: http://son-gtkusr:5600
    verbs: [ get, post, patch, put, delete, options, header ]   
  /sessions(/?|/*):
    site: http://tng-common:5200
    verbs: [ post, delete ]   
  /packages(/?|/*):
    #filters:
    #  - GenerateInternalId
    #  - SwapToExternalID
    #site: http://tng-common:5200
    site: http://localhost:5000 #son-gtkpkg:5100
    verbs: [ get, post, patch, put, delete, options, header ]
    auth: true  
  /services(/?|/*):
    #site: http://tng-common:5200
    site: http://localhost:5000 #son-gtksrv:5300
    #site: http://catalogues:4002/catalogues/api/v2/network-services
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /functions(/?|/*):
    #site: http://tng-common:5200
    site: http://son-gtkfnct:5500
    #site: http://catalogues:4002/catalogues/api/v2/vnfs
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /vims:
    site: http://son-gtkvim:5700
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /records(/?|/*):
    site: http://son-gtkrec:5800
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /licenses:
    site: http://son-gtklic:5900
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /metrics:
    site: http://son-monitor:8000/api/v1/
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true
  /slices(/?|/*):
    site: http://tng-slices
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /policies(/?|/*):
    site: http://tng-policies
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  
  /slas(/?|/*):
    site: http://tng-slas
    verbs: [ get, post, patch, put, delete, options, header ]   
    auth: true  